### ISSUE TITLE
*.umx tracker modules doesn't playback properly

### ISSUE THREAD

**Issue by rastamangames** [ZDoom/ZMusic#39]
Just insert this file into ***.wad** and/or ***.pk3** and attach it to the level via **MAPINFO** lump:
[TOTALIZA.umx](https://drive.google.com/file/d/1nkGgiKZkeYZp0aBx86v7bJ_4se1xbfiq/view?usp=sharing)

Result is this (both in GZDoom and LZDoom):
https://streamable.com/wf4g5m

You can try to do the same with this file as well:
[RUN.umx](https://drive.google.com/file/d/1ysbitH-FM3UbdPXTGPnoT2uWOVgAiqSv/view?usp=sharing)

Extracted ***.xm** and ***.it** modules works fine, but I presume that ***.umx** module must work fine too.
Even in elder Odamex ***.umx** tracker modules has proper playback.

**Comment by coelckers** [comment]
This is not surprising. Unreal container support was never implemented in the module loader.

**Comment by madame-rachelle** [comment]
I actually thought it was, hence why I asked for the report here, I was surprised it didn't reject the file outright due to lack of support. Still - I know someone who is familiar with Unreal formats, she might be able to do container support.

**Comment by OrdinaryMagician** [comment]
Yes, I am familiar with Unreal formats. Which is why I'd suggest for this to not be supported, and encourage people to simply unpack the umx files using other tools.

**Comment by OrdinaryMagician** [comment]
Otherwise, the only way UMX support could happen is if foo_dumb was replaced with libopenmpt.

**Comment by madame-rachelle** [comment]
Guess the solution here is to extract the files then - my bad, I actually did think container support was added.

**Comment by Cacodemon345** [comment]
libxmp should support UMX formats with the recent 1.1.14 release, albeit tracker-only (no support for MP2/WAV music).
