### ISSUE TITLE
Fluidsynth cannot load patch files from unicode folders properly

### ISSUE THREAD

**Issue by madame-rachelle** [ZDoom/ZMusic#41]
![image](https://user-images.githubusercontent.com/18584402/185023096-3c4313e0-b200-45e3-8134-be106aa301ba.png)
To reproduce, simply do a "mklink /j (your-gzdoom-folder) 試験" from the command line, then cd into 試験 and run GZDoom from there.

**Comment by coelckers** [comment]
FluidSynth's file handling code is a mess. From the looks of it it should be UTF-8 but with this code it is hard to tell if some of it does not,work.

**Comment by coelckers** [comment]
Or maybe it's the double slash...?

**Comment by madame-rachelle** [comment]
The best way that I can think of to address this is to throw the patch set into a temporary folder and load it from there - even if it is via a symlink - but there is no guarantee that symlinks will be available in any temporary storage, nor that the temporary storage will be behind an ascii-conforming path name. This may have to be addressed directly in fluidsynth itself.

**Comment by coelckers** [comment]
I just checked and with the latest version of both GZDoom and ZMusic it does load the soundfont from a directory with such a name - conversion of UTF-8 to wide chars is properly performed before opening the file successfully.
