### ISSUE TITLE
Build failure at Windows 10 MinGW 13 compiler.

### ISSUE THREAD

**Issue by DeadlyPresence** [ZDoom/ZMusic#59]
Hello.
I have a few troubles with building at mentioned system.

source/musicformats/win32/i_cd.cpp
137: L"ZMusic CD Player" ->"ZMusic CD Player";
232: (LPCWSTR)MCI_DEVTYPE_CD_AUDIO -> (LPCSTR)MCI_DEVTYPE_CD_AUDIO;
239: ident -> (LPCSTR)ident;
377: ident -> (LPSTR)ident;

source/mididevices/music_win_mididevice.cpp
+43: #include <stdexcept>

**Comment by coelckers** [comment]
Please post a complete error message. This fragment is rather useless.
Also please note that MinGW is not an officially supported compiler as its Windows headers are of rather poor quality.

**Comment by DeadlyPresence** [comment]
Here's log.
[log.txt](https://github.com/user-attachments/files/15775598/log.txt)
